---
- hosts: localhost
  tasks:
  - name: Create a new provider in ManageIQ
    manageiq_provider:
      name: 'EngLab Prometheus'
      type: 'Openshift'
      endpoints:
        default:
          auth_key: '{{ mgmt_infra_sa_token }}'
          hostname: '{{ oo_first_master.0 }}'
          port: 8443
          verify_ssl: False
        metrics:
          role: 'prometheus'
          hostname: '{{ prometheus_route }}'
          port: 443
          verify_ssl: False
      manageiq_connection:
        url: "https://{{ httpd_route }}"
        username: 'admin'
        password: 'smartvm'
        verify_ssl: False
