---
- hosts: localhost
  connection: local
  tasks:
  - name: Create a new provider in ManageIQ
    manageiq_provider:
      name: 'EngLab Prometheus'
      type: 'Openshift'
      provider:
        auth_key: '{{ mgmt_infra_sa_token }}'
        hostname: '{{ oo_first_master }}'
        port: 8443
        verify_ssl: true
        security_protocol: "ssl-with-validation-custom-ca"
        certificate_authority: |
          -----BEGIN CERTIFICATE-----
          MIIC6jCCAdKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
          c2hpZnQtc2lnbmVyQDE1MDY5NTk1OTkwHhcNMTcxMDAyMTU1MzE5WhcNMjIxMDAx
          MTU1MzIwWjAmMSQwIgYDVQQDDBtvcGVuc2hpZnQtc2lnbmVyQDE1MDY5NTk1OTkw
          ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDq7z6tUIzL+V3VFeNu3Dmo
          mtcyIS/993oisY2Osbjd5VQYlN+pSIMX7sagO2WzIWOth3Ef2eM+HQjKc/qdvXEQ
          Y4gARRSsiGgRG4bi3nSuJzhcOefuJuzXJWMGOXYJtuF1Gm+LtbkFGeTiUgBDUVIF
          Sc7PFFLQgws1c4FraA92np0XHdShbtW/PoEn/1MJyaLz/gnEcllaj55Fd8jD2yR/
          QY8GyflQLIcIXR6cqqyzmM6FVwBPj5wikcp1lrfgyZzujf96pi2WX3Fpl5YSN5aE
          pNBVQGIBoIEP4EqwiNFBei5vMmPuEII9Sp6/k8dtgW6bF+YVor55ILFIEkfgxOXT
          AgMBAAGjIzAhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MA0GCSqG
          SIb3DQEBCwUAA4IBAQACoIFVTtgFETXXjMmm7iis3QoMjUwXwfsuPt+yqETMyDTc
          JmoKLacvN0wPvPryvYd7z8U60mq8zlm2c8RujbdzBq9b5qjuII/nYgJWK2n6Y0Ld
          eKkDGBLkAKuXycZMpnhx7f0hzK9bm3Gz1MJwlfPJ3NtfXKkFu4BftarynbI1pq/B
          MbchxIPw7y0cJicxkVgTVcZGTu0W97vN4gFNDm6rwAVj90Ta+vJ0DlXTHEs4V+4F
          lUCw6pfb21rn6Pg9tRPqyj9Op66Y/XZMJVNenKqxruxPQhCLpNYiq/aCH3RL31Ce
          gi5nrAWI+9Kp/TimAfUzKpznlnGXR2FSjSQueGX0
          -----END CERTIFICATE-----
      metrics:
        auth_key: '{{ mgmt_infra_sa_token }}'
        role: 'prometheus'
        hostname: '{{ prometheus_route }}'
        port: 443
        verify_ssl: true
        security_protocol: "ssl-with-validation-custom-ca"
        certificate_authority: |
          -----BEGIN CERTIFICATE-----
          MIIC6jCCAdKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
          c2hpZnQtc2lnbmVyQDE1MDY5NTk1OTkwHhcNMTcxMDAyMTU1MzE5WhcNMjIxMDAx
          MTU1MzIwWjAmMSQwIgYDVQQDDBtvcGVuc2hpZnQtc2lnbmVyQDE1MDY5NTk1OTkw
          ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDq7z6tUIzL+V3VFeNu3Dmo
          mtcyIS/993oisY2Osbjd5VQYlN+pSIMX7sagO2WzIWOth3Ef2eM+HQjKc/qdvXEQ
          Y4gARRSsiGgRG4bi3nSuJzhcOefuJuzXJWMGOXYJtuF1Gm+LtbkFGeTiUgBDUVIF
          Sc7PFFLQgws1c4FraA92np0XHdShbtW/PoEn/1MJyaLz/gnEcllaj55Fd8jD2yR/
          QY8GyflQLIcIXR6cqqyzmM6FVwBPj5wikcp1lrfgyZzujf96pi2WX3Fpl5YSN5aE
          pNBVQGIBoIEP4EqwiNFBei5vMmPuEII9Sp6/k8dtgW6bF+YVor55ILFIEkfgxOXT
          AgMBAAGjIzAhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MA0GCSqG
          SIb3DQEBCwUAA4IBAQACoIFVTtgFETXXjMmm7iis3QoMjUwXwfsuPt+yqETMyDTc
          JmoKLacvN0wPvPryvYd7z8U60mq8zlm2c8RujbdzBq9b5qjuII/nYgJWK2n6Y0Ld
          eKkDGBLkAKuXycZMpnhx7f0hzK9bm3Gz1MJwlfPJ3NtfXKkFu4BftarynbI1pq/B
          MbchxIPw7y0cJicxkVgTVcZGTu0W97vN4gFNDm6rwAVj90Ta+vJ0DlXTHEs4V+4F
          lUCw6pfb21rn6Pg9tRPqyj9Op66Y/XZMJVNenKqxruxPQhCLpNYiq/aCH3RL31Ce
          gi5nrAWI+9Kp/TimAfUzKpznlnGXR2FSjSQueGX0
          -----END CERTIFICATE-----
      alerts:
        auth_key: '{{ mgmt_infra_sa_token }}'
        role: 'prometheus_alerts'
        hostname: '{{ alerts_route }}'
        port: 443
        verify_ssl: true
        security_protocol: "ssl-with-validation-custom-ca"
        certificate_authority: |
          -----BEGIN CERTIFICATE-----
          MIIC6jCCAdKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
          c2hpZnQtc2lnbmVyQDE1MDY5NTk1OTkwHhcNMTcxMDAyMTU1MzE5WhcNMjIxMDAx
          MTU1MzIwWjAmMSQwIgYDVQQDDBtvcGVuc2hpZnQtc2lnbmVyQDE1MDY5NTk1OTkw
          ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDq7z6tUIzL+V3VFeNu3Dmo
          mtcyIS/993oisY2Osbjd5VQYlN+pSIMX7sagO2WzIWOth3Ef2eM+HQjKc/qdvXEQ
          Y4gARRSsiGgRG4bi3nSuJzhcOefuJuzXJWMGOXYJtuF1Gm+LtbkFGeTiUgBDUVIF
          Sc7PFFLQgws1c4FraA92np0XHdShbtW/PoEn/1MJyaLz/gnEcllaj55Fd8jD2yR/
          QY8GyflQLIcIXR6cqqyzmM6FVwBPj5wikcp1lrfgyZzujf96pi2WX3Fpl5YSN5aE
          pNBVQGIBoIEP4EqwiNFBei5vMmPuEII9Sp6/k8dtgW6bF+YVor55ILFIEkfgxOXT
          AgMBAAGjIzAhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MA0GCSqG
          SIb3DQEBCwUAA4IBAQACoIFVTtgFETXXjMmm7iis3QoMjUwXwfsuPt+yqETMyDTc
          JmoKLacvN0wPvPryvYd7z8U60mq8zlm2c8RujbdzBq9b5qjuII/nYgJWK2n6Y0Ld
          eKkDGBLkAKuXycZMpnhx7f0hzK9bm3Gz1MJwlfPJ3NtfXKkFu4BftarynbI1pq/B
          MbchxIPw7y0cJicxkVgTVcZGTu0W97vN4gFNDm6rwAVj90Ta+vJ0DlXTHEs4V+4F
          lUCw6pfb21rn6Pg9tRPqyj9Op66Y/XZMJVNenKqxruxPQhCLpNYiq/aCH3RL31Ce
          gi5nrAWI+9Kp/TimAfUzKpznlnGXR2FSjSQueGX0
          -----END CERTIFICATE-----
      manageiq_connection:
        url: "https://{{ httpd_route }}"
        username: 'admin'
        password: 'smartvm'
        verify_ssl: false
