---
- hosts: localhost
  connection: local
  tasks:
  - name: Create a new provider in ManageIQ
    manageiq_provider:
      name: 'EngLab Prometheus'
      type: 'Openshift'
      provider:
        auth_key: '{{ mgmt_infra_sa_token }}'
        hostname: '{{ oo_first_master }}'
        port: 8443
        verify_ssl: true
        security_protocol: "ssl-with-validation-custom-ca"
        certificate_authority: |
          -----BEGIN CERTIFICATE-----
          MIIC6jCCAdKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
          c2hpZnQtc2lnbmVyQDE1MDYzNjY5MjgwHhcNMTcwOTI1MTkxNTI3WhcNMjIwOTI0
          MTkxNTI4WjAmMSQwIgYDVQQDDBtvcGVuc2hpZnQtc2lnbmVyQDE1MDYzNjY5Mjgw
          ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDphiDhbDYaGfNeBS3VphQe
          1EJxtE8+g0K3x4iOEga7ylosrQiTZgu+JYPVTs5rLNwIu8t5mZ0N7BrNgoJFDjcO
          pCzuWx3vaqpks5Gj9bd223yTUSfE4V2a7GkvhNhg66fuZUW8+hQ7UeX82Z8vCmGu
          CLQBt60eO23OeQtXM1YagNyZTxZUKUxU2g73eN29kv8ad1eEUHE6EtK0jW8OOWYL
          +kEIOcnuwAAhytyp9Cv5Ft5hPqU+x5AKhquX2qOMtl0bjFBaVrzOILgcfTkTUGd5
          HAtXfFObBnlOuvJJSwYUHSf28tyZXHHqVpl63kNq8SJDQtrKhwwQv2+lf8yVmJiV
          AgMBAAGjIzAhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MA0GCSqG
          SIb3DQEBCwUAA4IBAQC/q+QHyFvekoGDAde1pU0vUB0Q/rted48XUjpkVymM/030
          7mE8hZcyvF+TpiueM70ZcYVKdCbeD6hawPqTMAzgkkXprh5XkXA3jQNb3Pdkkb4u
          kNr/PdlqGBj683tL68UeKyT+Sz1L7P6rxv2d3k0z5/LiA19F+W6N25z5O4rct13B
          +Ts83aTLZT+ciI53XezmwtkoEacydFpKof9c67bgurXFWggN1FxcGSXS2dO1v1OQ
          hQGgeBVRs0J9L1ZxxpQQo95Af+DdrVzW6o+niyJ7a77fWYDiDa7ylTsE68Xd/U1g
          sKW04n5L6nm+VNHpr7kYy/5AUJaANurF+wMoP1yS
          -----END CERTIFICATE-----
      metrics:
        auth_key: '{{ mgmt_infra_sa_token }}'
        role: 'prometheus'
        hostname: '{{ prometheus_route }}'
        port: 443
        verify_ssl: true
        security_protocol: "ssl-with-validation-custom-ca"
        certificate_authority: |
          -----BEGIN CERTIFICATE-----
          MIIC6jCCAdKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
          c2hpZnQtc2lnbmVyQDE1MDYzNjY5MjgwHhcNMTcwOTI1MTkxNTI3WhcNMjIwOTI0
          MTkxNTI4WjAmMSQwIgYDVQQDDBtvcGVuc2hpZnQtc2lnbmVyQDE1MDYzNjY5Mjgw
          ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDphiDhbDYaGfNeBS3VphQe
          1EJxtE8+g0K3x4iOEga7ylosrQiTZgu+JYPVTs5rLNwIu8t5mZ0N7BrNgoJFDjcO
          pCzuWx3vaqpks5Gj9bd223yTUSfE4V2a7GkvhNhg66fuZUW8+hQ7UeX82Z8vCmGu
          CLQBt60eO23OeQtXM1YagNyZTxZUKUxU2g73eN29kv8ad1eEUHE6EtK0jW8OOWYL
          +kEIOcnuwAAhytyp9Cv5Ft5hPqU+x5AKhquX2qOMtl0bjFBaVrzOILgcfTkTUGd5
          HAtXfFObBnlOuvJJSwYUHSf28tyZXHHqVpl63kNq8SJDQtrKhwwQv2+lf8yVmJiV
          AgMBAAGjIzAhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MA0GCSqG
          SIb3DQEBCwUAA4IBAQC/q+QHyFvekoGDAde1pU0vUB0Q/rted48XUjpkVymM/030
          7mE8hZcyvF+TpiueM70ZcYVKdCbeD6hawPqTMAzgkkXprh5XkXA3jQNb3Pdkkb4u
          kNr/PdlqGBj683tL68UeKyT+Sz1L7P6rxv2d3k0z5/LiA19F+W6N25z5O4rct13B
          +Ts83aTLZT+ciI53XezmwtkoEacydFpKof9c67bgurXFWggN1FxcGSXS2dO1v1OQ
          hQGgeBVRs0J9L1ZxxpQQo95Af+DdrVzW6o+niyJ7a77fWYDiDa7ylTsE68Xd/U1g
          sKW04n5L6nm+VNHpr7kYy/5AUJaANurF+wMoP1yS
          -----END CERTIFICATE-----
      alerts:
        auth_key: '{{ mgmt_infra_sa_token }}'
        role: 'prometheus_alerts'
        hostname: '{{ alerts_route }}'
        port: 443
        verify_ssl: true
        security_protocol: "ssl-with-validation-custom-ca"
        certificate_authority: |
          -----BEGIN CERTIFICATE-----
          MIIC6jCCAdKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
          c2hpZnQtc2lnbmVyQDE1MDYzNjY5MjgwHhcNMTcwOTI1MTkxNTI3WhcNMjIwOTI0
          MTkxNTI4WjAmMSQwIgYDVQQDDBtvcGVuc2hpZnQtc2lnbmVyQDE1MDYzNjY5Mjgw
          ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDphiDhbDYaGfNeBS3VphQe
          1EJxtE8+g0K3x4iOEga7ylosrQiTZgu+JYPVTs5rLNwIu8t5mZ0N7BrNgoJFDjcO
          pCzuWx3vaqpks5Gj9bd223yTUSfE4V2a7GkvhNhg66fuZUW8+hQ7UeX82Z8vCmGu
          CLQBt60eO23OeQtXM1YagNyZTxZUKUxU2g73eN29kv8ad1eEUHE6EtK0jW8OOWYL
          +kEIOcnuwAAhytyp9Cv5Ft5hPqU+x5AKhquX2qOMtl0bjFBaVrzOILgcfTkTUGd5
          HAtXfFObBnlOuvJJSwYUHSf28tyZXHHqVpl63kNq8SJDQtrKhwwQv2+lf8yVmJiV
          AgMBAAGjIzAhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MA0GCSqG
          SIb3DQEBCwUAA4IBAQC/q+QHyFvekoGDAde1pU0vUB0Q/rted48XUjpkVymM/030
          7mE8hZcyvF+TpiueM70ZcYVKdCbeD6hawPqTMAzgkkXprh5XkXA3jQNb3Pdkkb4u
          kNr/PdlqGBj683tL68UeKyT+Sz1L7P6rxv2d3k0z5/LiA19F+W6N25z5O4rct13B
          +Ts83aTLZT+ciI53XezmwtkoEacydFpKof9c67bgurXFWggN1FxcGSXS2dO1v1OQ
          hQGgeBVRs0J9L1ZxxpQQo95Af+DdrVzW6o+niyJ7a77fWYDiDa7ylTsE68Xd/U1g
          sKW04n5L6nm+VNHpr7kYy/5AUJaANurF+wMoP1yS
          -----END CERTIFICATE-----
      manageiq_connection:
        url: "https://{{ httpd_route }}"
        username: 'admin'
        password: 'smartvm'
        verify_ssl: false
