---
- hosts: localhost
  connection: local
  tasks:
  - name: Create a new provider in ManageIQ
    manageiq_provider:
      name: 'EngLab Prometheus'
      type: 'Openshift'
      provider:
        auth_key: '{{ mgmt_infra_sa_token }}'
        hostname: '{{ oo_first_master }}'
        port: 8443
        verify_ssl: true
        security_protocol: "ssl-with-validation-custom-ca"
        certificate_authority: |
          -----BEGIN CERTIFICATE-----
          MIIC6jCCAdKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
          c2hpZnQtc2lnbmVyQDE1MDU4MzIwNTUwHhcNMTcwOTE5MTQ0MDU0WhcNMjIwOTE4
          MTQ0MDU1WjAmMSQwIgYDVQQDDBtvcGVuc2hpZnQtc2lnbmVyQDE1MDU4MzIwNTUw
          ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDZiz4sAW15FOL1/fsLAwwW
          9uYTC6iiSTH8aWiZ6Wcs0N+Bf6dZ4malJNyUvOVYv4UFlc1EYvYSg/PxMoCb83Zi
          TUxQ4EgFoZ3x1CzFwQnB5zFOn98c7AUUK2Bqzh6Ui8Ek/7N/AxgXN/nwrciFdSWO
          j+wTmVx8OoX0hCQec5uIbaZHuqvx65bpSiFnzcrPzckKY+IKrI4aKfffy2PyATOd
          3m3LLF1/7d+RPA4VCPgm6Bt6ouK8OGjQNvSNvjbLRMlHnoGHPJAA8gK6zVTHXfJg
          3bAiHH5qlGR0hbwCjUC243tyb1g3OzUtUMpV7su5LUnY6xRp5XUYDJ45TIB2abRl
          AgMBAAGjIzAhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MA0GCSqG
          SIb3DQEBCwUAA4IBAQA9g/SeRlZdS7HDL0xASyfUQjBMQIxmE26ComLUyrvw8EBb
          /YSQ5grkx46CfdOSgl94wyYb9Zkx/Qkmaf9L6rV2R4x9gR66pQW9i/u9AHjuRDUS
          /00WCUtvIkJWudRuxnc9pQs4AQA0Az8nriRXD6bmbdqKAlPaGCwZ4M5nmxG8PiDO
          /Q+B+Xr1Q81j3s4X2mOTB9K4ifxMo1RPbw7Y39OIyoS2QdtjJBOy1Z+4PEe++ZHp
          1X8DYDiIETbNn0aPtGM2FNsq9Z3Xd+LSGSKEiVVzpCSIJv1XKh3d97l/juqqbS3q
          G2kAvupJCid77xPf7zbmzHP2NqMhIzdFLlh7+zG6
          -----END CERTIFICATE-----
      metrics:
        auth_key: '{{ mgmt_infra_sa_token }}'
        role: 'prometheus'
        hostname: '{{ prometheus_route }}'
        port: 443
        verify_ssl: true
        security_protocol: "ssl-with-validation-custom-ca"
        certificate_authority: |
          -----BEGIN CERTIFICATE-----
          MIIC6jCCAdKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
          c2hpZnQtc2lnbmVyQDE1MDU4MzIwNTUwHhcNMTcwOTE5MTQ0MDU0WhcNMjIwOTE4
          MTQ0MDU1WjAmMSQwIgYDVQQDDBtvcGVuc2hpZnQtc2lnbmVyQDE1MDU4MzIwNTUw
          ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDZiz4sAW15FOL1/fsLAwwW
          9uYTC6iiSTH8aWiZ6Wcs0N+Bf6dZ4malJNyUvOVYv4UFlc1EYvYSg/PxMoCb83Zi
          TUxQ4EgFoZ3x1CzFwQnB5zFOn98c7AUUK2Bqzh6Ui8Ek/7N/AxgXN/nwrciFdSWO
          j+wTmVx8OoX0hCQec5uIbaZHuqvx65bpSiFnzcrPzckKY+IKrI4aKfffy2PyATOd
          3m3LLF1/7d+RPA4VCPgm6Bt6ouK8OGjQNvSNvjbLRMlHnoGHPJAA8gK6zVTHXfJg
          3bAiHH5qlGR0hbwCjUC243tyb1g3OzUtUMpV7su5LUnY6xRp5XUYDJ45TIB2abRl
          AgMBAAGjIzAhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MA0GCSqG
          SIb3DQEBCwUAA4IBAQA9g/SeRlZdS7HDL0xASyfUQjBMQIxmE26ComLUyrvw8EBb
          /YSQ5grkx46CfdOSgl94wyYb9Zkx/Qkmaf9L6rV2R4x9gR66pQW9i/u9AHjuRDUS
          /00WCUtvIkJWudRuxnc9pQs4AQA0Az8nriRXD6bmbdqKAlPaGCwZ4M5nmxG8PiDO
          /Q+B+Xr1Q81j3s4X2mOTB9K4ifxMo1RPbw7Y39OIyoS2QdtjJBOy1Z+4PEe++ZHp
          1X8DYDiIETbNn0aPtGM2FNsq9Z3Xd+LSGSKEiVVzpCSIJv1XKh3d97l/juqqbS3q
          G2kAvupJCid77xPf7zbmzHP2NqMhIzdFLlh7+zG6
          -----END CERTIFICATE-----
      alerts:
        auth_key: '{{ mgmt_infra_sa_token }}'
        role: 'prometheus_alerts'
        hostname: '{{ alerts_route }}'
        port: 443
        verify_ssl: true
        security_protocol: "ssl-with-validation-custom-ca"
        certificate_authority: |
          -----BEGIN CERTIFICATE-----
          MIIC6jCCAdKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
          c2hpZnQtc2lnbmVyQDE1MDU4MzIwNTUwHhcNMTcwOTE5MTQ0MDU0WhcNMjIwOTE4
          MTQ0MDU1WjAmMSQwIgYDVQQDDBtvcGVuc2hpZnQtc2lnbmVyQDE1MDU4MzIwNTUw
          ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDZiz4sAW15FOL1/fsLAwwW
          9uYTC6iiSTH8aWiZ6Wcs0N+Bf6dZ4malJNyUvOVYv4UFlc1EYvYSg/PxMoCb83Zi
          TUxQ4EgFoZ3x1CzFwQnB5zFOn98c7AUUK2Bqzh6Ui8Ek/7N/AxgXN/nwrciFdSWO
          j+wTmVx8OoX0hCQec5uIbaZHuqvx65bpSiFnzcrPzckKY+IKrI4aKfffy2PyATOd
          3m3LLF1/7d+RPA4VCPgm6Bt6ouK8OGjQNvSNvjbLRMlHnoGHPJAA8gK6zVTHXfJg
          3bAiHH5qlGR0hbwCjUC243tyb1g3OzUtUMpV7su5LUnY6xRp5XUYDJ45TIB2abRl
          AgMBAAGjIzAhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MA0GCSqG
          SIb3DQEBCwUAA4IBAQA9g/SeRlZdS7HDL0xASyfUQjBMQIxmE26ComLUyrvw8EBb
          /YSQ5grkx46CfdOSgl94wyYb9Zkx/Qkmaf9L6rV2R4x9gR66pQW9i/u9AHjuRDUS
          /00WCUtvIkJWudRuxnc9pQs4AQA0Az8nriRXD6bmbdqKAlPaGCwZ4M5nmxG8PiDO
          /Q+B+Xr1Q81j3s4X2mOTB9K4ifxMo1RPbw7Y39OIyoS2QdtjJBOy1Z+4PEe++ZHp
          1X8DYDiIETbNn0aPtGM2FNsq9Z3Xd+LSGSKEiVVzpCSIJv1XKh3d97l/juqqbS3q
          G2kAvupJCid77xPf7zbmzHP2NqMhIzdFLlh7+zG6
          -----END CERTIFICATE-----
      manageiq_connection:
        url: "https://{{ httpd_route }}"
        username: 'admin'
        password: 'smartvm'
        verify_ssl: false
