groups:
- name: example-rules
  interval: 30s # defaults to global interval
  rules:
  - alert: Node Down
    expr: up{job="kubernetes-nodes"} == 0
    annotations:
      miqTarget: "ContainerNode"
      severity: "HIGH"
      url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
      message: "{{$labels.instance}} is down"
      description: "{{$labels.instance}} is down_d"
  - alert: Too Many Pods
    expr: sum(kubelet_running_pod_count) > 50
    annotations:
      severity: "HIGH"
      url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
      message: "Too many pods! Please delete"
