apiVersion: v1
kind: Template
labels:
  template: postgres-nfs-pv
objects:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: miq-pv01
  spec:
    capacity:
      storage: 15Gi
    accessModes:
    - ReadWriteOnce
    nfs:
      path: "/exports/miq-pv01"
      server: "${NFS_HOST}"
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: miq-pv02
  spec:
    capacity:
      storage: 5Gi
    accessModes:
    - ReadWriteOnce
    nfs:
      path: "/exports/miq-pv02"
      server: "${NFS_HOST}"
parameters:
- name: NFS_HOST
  displayName: NFS Host
  required: true
  description: The IP or hostname of the NFS server.
